spring:
  datasource:
    url: jdbc:h2:mem:ace-nphc-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    include-message: always